# @package job.training_config.augmentation_config
augmentations:
  - KIND: RandomHorizontalFlip
    p: 0.5
  - KIND: RandomPhotometricDistort
    brightness: [0.95, 1.05]
    contrast: [0.85, 1.15]
    saturation: [0.8, 1.2]
    hue: [-0.01, 0.01]
    p: 0.5
  - KIND: RandomGrayscale
    p: 0.2
  - KIND: RandomGaussianBlur
    kernel_size: [3, 7]
    sigma: [0.1, 2.0]
    p: 0.3
  - KIND: RandomErasing
    p: 0.3
    scale: [0.02, 0.15]
    ratio: [0.3, 3.3]
    value: 0
